apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: hello-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-neg
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    anthos.cft.dev/autoneg: '{"name":"gke-http-lb-backend-default", "max_rate_per_endpoint":1000}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-nginx
  ports:
  - name: my-service-port
    protocol: TCP
    port: 80
    targetPort: 80
